[package]
name = "rust_axum"
version = "0.1.0"
edition = "2022"

[dependencies]
askama = "0.11"
axum = "0.5.15"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }